mediav2: use getMaxInputChannelCount() for android r and below
getInputChannelCountRanges() is introduced in android s. For versions
below invoking this method would raise java.lang.NoSuchMethodError. For
R and below, use an equivalent available method.

Bug: 443924982
Test: atest MctsMediaV2TestCases:AudioEncoderTest
Flag: TEST_ONLY
Change-Id: I6fb45157e0f32874bbb957467276c8ca6598d522