DO NOT MERGE: Disable hidden-api-checks for CtsDeviceStateManagerTestCases
This is needed to avoid NoSuchMethodErrors caused by tests trying to
access flagged APIs whose flags are not enabled in Android 14.

Bug: 341613785
Test: atest CtsDeviceStateManagerTestCases
Change-Id: Ic9bd1cbd507c53d20b1299be05edfc08205e9d07