Fixed SimpleIntentReceiverActivity.
It was crashing in some builds because Context.getuserId() was
throwing NoSuchMethodError.

Fixes: 183232033
Bug: 183427655

Test: m -j CtsIntentReceiverApp && adb install -t --user all $OUT/testcases/CtsIntentReceiverApp/*/CtsIntentReceiverApp.apk && adb shell am start com.android.cts.intent.receiver/.SimpleIntentReceiverActivity
Test: atest com.android.cts.devicepolicy.MixedDeviceOwnerTest#testSuspendPackage,testSuspendPackageWithPackageManager com.android.cts.devicepolicy.MixedManagedProfileOwnerTest#testSuspendPackage,testSuspendPackageWithPackageManager com.android.cts.devicepolicy.MixedProfileOwnerTest#testSuspendPackage,testSuspendPackageWithPackageManager

Change-Id: I96850cb542cf8107a4788584742610401431c6ff