Remove test annotations from base test class
The @RunWith/etc associated annotations aren't needed here, and using
them is causing the warning:

    InvalidTestClassError: Invalid test class
    'android.permission.cts.BaseNotificationListenerCheckTest'
    1. No runnable methods
    ...

The reason these aren't needed here is because this
test doesn't directly have any @Test methods. Rather, its inherited
classes do (and these inherited classes already correctly have these
annotations).

Change-Id: If05d009dc905e046a6f51760ac24c7f40a2fd663
Test: atest CtsPermissionTestCases CtsPermission3TestCases