Fix com.google.android.gts.devicepolicy.DeviceOwnerTest#testDevicePolicyManager failure on automotive devices.
Context.getUser() causes a NoSuchMethodError ERROR under
android.app.ReceiverRestrictedContext.
Changed mUser as String and added try/catch to avoid FATAL error.
Removed final keyword to avoid compile error.

Bug: 219868141
Test: atest -b -t com.google.android.gts.devicepolicy.DeviceOwnerTest#testDevicePolicyManager
Change-Id: I3371649a73bf075c2164aed0d76ec5ffe4014fac