DO NOT MERGE: Disable hidden-api-checks for CtsAutoFillServiceTestCases
This is needed to avoid NoSuchMethodErrors caused by tests trying to
access flagged APIs whose flags are not enabled in Android 14.

Bug: 341613603
Test: atest CtsAutoFillServiceTestCases
Change-Id: Ibdc36fe848d1210b1c2d4cb53540f85751593675