Revert "ITS: convert_image_to_numpy_array use cv2.imread"
This reverts commit d47c1b4101aed5ba8f681d7755ecf1f5c05dc4a4.

Reason for revert: Breaks scene7/test_multi_camera_switch with:
TypeError: Can't convert object of type 'PosixPath' to 'str' for 'filename'

Change-Id: Id87f1f3357b2ae1bd9bb182f43c17a186590c8f8