Resolve GSI failures where flag not found
We were seeing NoClassDefFoundError on referencing telecom flags on
older OS versions (Android V). Looks like this was due to mixed testing
where tests are run on older builds to ensure backwards compatibility.
Check the SDK level for the test before referencing the flags to avoid
the issue.

Bug: 440309972
Bug: 439953084
Flag: EXEMPT test fix
Test: atest BlockedNumberContractTest
Test: atest CallLogTest
Change-Id: I94df2766a3dd6efeb44d2f16cbd945aa692a202e