DO NOT MERGE: Disable hidden-api-checks for CtsPersistentDataBlockManagerTestCases
This is needed to avoid NoSuchMethodErrors caused by tests trying to
access flagged APIs whose flags are not enabled in Android 14.

Bug: 341342803
Test: atest CtsPersistentDataBlockManagerTestCases
Change-Id: I2df3f3f1b9a05b5fdf188faddfa8fc06d3dd3b36