Fix flagsOff Move API CTS tests
The various DefaultAccountAndState APIs will fail with NoSuchMethodError
if new_default_account_api_enabled isn't set

Bug: b/372095500
Test: atest android.provider.cts.contacts.ContactsContract_MoveToCloudDeviceContactsAccount
Flag: android.provider.new_default_account_api_enabled

 Changes to be committed:
	modified:   tests/tests/contactsprovider/src/android/provider/cts/contacts/ContactsContract_MoveToCloudDeviceContactsAccount.java

Change-Id: I3a0656cc431670d3cada79ec09dd8f5bd6d256af